import {
  bar_rolling,
  bars1,
  bending1,
  bending2,
  bending3,
  bending4,
  dne_machine,
  fiber_laser1,
  fiber_laser2,
  fiber_laser3,
  metal_rolling1,
  metal_rolling2,
  metal_rolling3,
  metal_welding1,
  metal_welding2,
  metal_welding3,
  metal_welding4,
  stock1,
  stock2,
  zigzag_sheets,
  setalco,
} from "@/assets";

const images = [
  bar_rolling,
  bars1,
  bending1,
  bending2,
  bending3,
  bending4,
  dne_machine,
  fiber_laser1,
  fiber_laser2,
  fiber_laser3,
  metal_rolling1,
  metal_rolling2,
  metal_rolling3,
  metal_welding1,
  metal_welding2,
  metal_welding3,
  metal_welding4,
  stock1,
  stock2,
  zigzag_sheets,
  setalco,
];
export default images;
